# Generated by Django 5.2.4 on 2025-11-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.CreateModel(
            name='InscripcionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Inscripción Activa')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('motivo_baja', models.CharField(blank=True, max_length=200, verbose_name='Motivo de Baja')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno', verbose_name='Alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Inscripción a Carrera',
                'verbose_name_plural': 'Inscripciones a Carreras',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'carrera')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='carreras',
            field=models.ManyToManyField(related_name='alumnos_inscritos', through='alumnos.InscripcionCarrera', to='carreras.carrera', verbose_name='Carreras'),
        ),
    ]
