# Generated by Django 5.2.6 on 2025-09-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('cursando', 'Cursando'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado'), ('abandono', 'Abandono'), ('baja', 'Baja')], default='inscripto', max_length=15, verbose_name='Estado')),
                ('activa', models.BooleanField(default=True, verbose_name='Inscripción Activa')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('motivo_baja', models.CharField(blank=True, max_length=100, verbose_name='Motivo de Baja')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='alumnos.alumno', verbose_name='Alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='materias.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
